VIA_ENABLE = yes
VIAL_ENABLE = yes
VIAL_INSECURE = yes

COMBO_ENABLE = yes
TAP_DANCE_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes

POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = pmw3360

MOUSEKEY_ENABLE = yes

SPLIT_POINTING_ENABLE = yes

BOOTLOADER = rp2040
MCU = RP2040
