/* RGB Matrix */
#undef RGB_MATRIX_ENABLE
#define RGB_MATRIX_ENABLE true
#undef RGB_MATRIX_LED_COUNT
#define RGB_MATRIX_LED_COUNT 58
#undef RGB_MATRIX_SPLIT
#define RGB_MATRIX_SPLIT { 29, 29 }
#undef RGB_MATRIX_MAXIMUM_BRIGHTNESS
#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 150

// Добавлены недостающие определения для WS2812
#define RGB_DI_PIN GP0
#define DRIVER_LED_TOTAL 58
#define RGB_MATRIX_STARTUP_MODE RGB_MATRIX_SOLID_COLOR

#define RGB_MATRIX_KEYPRESSES
#define RGB_MATRIX_FRAMEBUFFER_EFFECTS
