# Платформа для Splinky (RP2040)
MCU = RP2040
BOARD = GENERIC_RP_RP2040

# Включаем основные функции
SPLIT_KEYBOARD = yes
MOUSEKEY_ENABLE = yes
POINTING_DEVICE_ENABLE = yes
RGB_MATRIX_ENABLE = yes
VIA_ENABLE = yes

# Драйверы
POINTING_DEVICE_DRIVER = pmw3360
RGB_MATRIX_DRIVER = ws2812
SERIAL_DRIVER = vendor
