# Processor configuration
MCU = RP2040
BOOTLOADER = rp2040
ARCH = ARMV6-M
PLATFORM = ARM
ARM_GCC_VERSION = 10

# Core features
SPLIT_KEYBOARD = yes
SERIAL_DRIVER = vendor

# RGB features
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_KEYPRESSES = yes
RGB_MATRIX_FRAMEBUFFER_EFFECTS = yes

# Pointing device
POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = pmw3360
POINTING_DEVICE_INVERT_X = yes

# VIA support
VIA_ENABLE = yes
