name: Build Vial Firmware
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: QMK Build
        uses: qmk/qmk-action@v5
        with:
          command: compile
          container: ghcr.io/qmk/qmk_cli
          keyboard: bastardkb/charybdis/4x6/v2/splinky_2
          keymap: vial

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Charybdis_4x6_Vial
          path: |
            *.uf2
            *.bin
            *.hex
