name: Build Vial Firmware
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build Firmware
        run: |
          git config --global --add safe.directory $(pwd)
          qmk compile -kb bastardkb/charybdis/4x6/v2/splinky_2 -km vial

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Charybdis_4x6_Vial
          path: |
            *.uf2
            *.bin
            *.hex
