name: QMK Build (Clean Overlay)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your files
        uses: actions/checkout@v4

      - name: Setup Clean QMK
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi binutils-arm-none-eabi libnewlib-arm-none-eabi python3-pip
          python3 -m pip install qmk milc
          # Скачиваем "заводской" QMK
          git clone https://github.com /home/runner/qmk_firmware
          qmk config user.qmk_home=/home/runner/qmk_firmware
          # Говорим QMK искать твою папку keyboards в текущем месте
          qmk config user.overlay_dir=$(pwd)
          qmk git-submodule

      - name: Compile & Breadcrumbs
        run: |
          # Собираем твою раскладку wellum на базе стандартного 4x6
          qmk compile -kb bastardkb/charybdis/4x6 -km wellum

          # Сбор хлебных крошек
          find .build -name "info_config.h" -exec cp {} build_diag_final.txt \; || echo "No config"

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: charybdis-final-firmware
          path: |
            *.uf2
            *.txt
